### ISSUE TITLE
cd image

### ISSUE THREAD

**Issue by tom-thompson** [dwalizer/wonderwitch#1]
i just picked up a dev kit, but i have the older [yellow] cd without the color libraries. any chance you'd be willing to rip the blue one and push it to archive.org?

**Comment by dwalizer** [comment]
Hey, sorry for the slow response on this.  I'd have to find where I put the kit (I think it's currently stored in my basement).  Have you already found a source for the color libraries?

**Comment by tom-thompson** [comment]
I have yeah. Thanks for responding.
